### ISSUE TITLE
`Button` component not compatible with tailwind's content configuration

### ISSUE THREAD

**Issue by Brian3647** [folkip/comoki#7]
![image](https://user-images.githubusercontent.com/73384214/152949592-484d3341-e72f-4491-be34-1c4bb3ae6e17.png)

[This line](https://github.com/folkip/comoki/blob/main/src/components/Buttons/Button.svelte#L8) should be updated.

**Comment by UltiRequiem** [comment]
It works on development lol

I will work on this thanks!

**Comment by Brian3647** [comment]
> It works on development lol
> 
> I will work on this thanks!

@UltiRequiem That's because the css purgue only applies in production. Also it may not be on

**Comment by UltiRequiem** [comment]
Just discover that if I put `closes #n` in the commit message It will do it automatically

![image](https://user-images.githubusercontent.com/71897736/153068706-c10a48fe-4486-4ed1-b06a-287c5c7c257f.png)
 
Is working now btw
